# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               Jingyi Xie
description:         Software Engineer
url:                 http://jingyi-xie.com
baseurl:             ''
paginate:            5

# Plugins, Tags, Categories and Analytics  
plugins:          [jekyll-paginate]

# About/contact
author:
  name:              Jingyi Xie
  url:               https://www.linkedin.com/in/jingyi-xie-duke
  email:             jingyi.xie@duke.edu