# Setup
title:            Jingyi Xie
description:      Software Engineer
url:              https://jingyi-xie.com
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Jingyi Xie'
  url:            https://www.linkedin.com/in/jingyi-xie-duke

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
